unbind C-b
set -g prefix C-a

set -g mouse on

set -g extended-keys on
set -g history-limit 10000

set -g base-index 1
set -g pane-base-index 1

# Status Style
set -g status-style 'bg=colour236'
set -g window-status-style 'bg=colour236,fg=colour208'
set -g window-status-format ' #I:#W '
set -g window-status-current-style 'bg=colour208,fg=colour236'
set -g window-status-current-format ' #I:#W#{?window_zoomed_flag,+,} '

set -g status-right '#(whoami)@#H'

bind a last-window
bind C-a last-window
bind , command-prompt -p "rename-window:" "rename-window '%%'"

# Open new panes in the current pane's working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
